/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as CriptoactivosRouteImport } from './routes/criptoactivos'
import { Route as CotizacionRouteImport } from './routes/cotizacion'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgroindustriaRouteImport } from './routes/agroindustria'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const CriptoactivosRoute = CriptoactivosRouteImport.update({
  id: '/criptoactivos',
  path: '/criptoactivos',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionRoute = CotizacionRouteImport.update({
  id: '/cotizacion',
  path: '/cotizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgroindustriaRoute = AgroindustriaRouteImport.update({
  id: '/agroindustria',
  path: '/agroindustria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agroindustria': typeof AgroindustriaRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/cotizacion': typeof CotizacionRoute
  '/criptoactivos': typeof CriptoactivosRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agroindustria': typeof AgroindustriaRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/cotizacion': typeof CotizacionRoute
  '/criptoactivos': typeof CriptoactivosRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agroindustria': typeof AgroindustriaRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/cotizacion': typeof CotizacionRoute
  '/criptoactivos': typeof CriptoactivosRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agroindustria'
    | '/blog'
    | '/contacto'
    | '/cotizacion'
    | '/criptoactivos'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agroindustria'
    | '/blog'
    | '/contacto'
    | '/cotizacion'
    | '/criptoactivos'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/agroindustria'
    | '/blog'
    | '/contacto'
    | '/cotizacion'
    | '/criptoactivos'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgroindustriaRoute: typeof AgroindustriaRoute
  BlogRoute: typeof BlogRoute
  ContactoRoute: typeof ContactoRoute
  CotizacionRoute: typeof CotizacionRoute
  CriptoactivosRoute: typeof CriptoactivosRoute
  NosotrosRoute: typeof NosotrosRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  ServiciosRoute: typeof ServiciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criptoactivos': {
      id: '/criptoactivos'
      path: '/criptoactivos'
      fullPath: '/criptoactivos'
      preLoaderRoute: typeof CriptoactivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizacion': {
      id: '/cotizacion'
      path: '/cotizacion'
      fullPath: '/cotizacion'
      preLoaderRoute: typeof CotizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agroindustria': {
      id: '/agroindustria'
      path: '/agroindustria'
      fullPath: '/agroindustria'
      preLoaderRoute: typeof AgroindustriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgroindustriaRoute: AgroindustriaRoute,
  BlogRoute: BlogRoute,
  ContactoRoute: ContactoRoute,
  CotizacionRoute: CotizacionRoute,
  CriptoactivosRoute: CriptoactivosRoute,
  NosotrosRoute: NosotrosRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  ServiciosRoute: ServiciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
